version: 1

services:
  - name: rioasia
    type: web
    env: node
    plan: free
    region: oregon
    repo: https://github.com/chubay008-dev/rio_fmcg_try
    branch: main

    buildCommand: npm ci && npm run build
    startCommand: npm start

    envVars:
      - key: NODE_VERSION
        value: "20"

      - key: NEXT_PUBLIC_SUPABASE_URL
        value: https://kilhcgsanxqocussxuqb.supabase.co

      - key: NEXT_PUBLIC_SUPABASE_ANON_KEY
        value: sb_publishable_L6vHPvlw9JgLL_00bgaITg_RBflwG5p

      - key: NEXT_PUBLIC_ZALO_CHAT_LINK
        value: https://zalo.me/r/botcreator/

      - key: ZALO_BOT_TOKEN
        value: 4519661879217951552:xiFRyBHlTJtBwDoEjvzfeZcjtLXVPtbHBfIOEWRshccqQpLRHbrkNXBrYYaayzwP

      - key: ZALO_BOT_WEBHOOK_SECRET
        value: rioasia@2026

    healthCheckPath: /api/zalo/webhook
    autoDeploy: true
